check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.26.0"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "s2i-anaconda-notebook"
  registry-secret: "thoth-station-thoth-pusher-secret"
